# Generated by Django 3.1.5 on 2021-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPMData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_code', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=200)),
                ('ppm_data_added', models.DateField(auto_now_add=True)),
                ('total_number_of_lot', models.IntegerField()),
                ('total_number_of_lot_rejected', models.IntegerField()),
            ],
        ),
    ]
