# Generated by Django 3.1.5 on 2021-08-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MouldQuality', '0002_damagetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagetype',
            old_name='mould_name',
            new_name='damage_name',
        ),
    ]
