# Generated by Django 3.1.5 on 2021-08-10 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MouldQuality', '0003_auto_20210808_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrack',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=200)),
                ('audit_type', models.CharField(max_length=20)),
                ('tools', models.IntegerField()),
                ('no_of_machine', models.IntegerField()),
                ('both_side_done', models.BooleanField(verbose_name=False)),
                ('godrej_auitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Audit_godrej_user', to=settings.AUTH_USER_MODEL)),
                ('supplier_audito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aduit_supplier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
