# Generated by Django 3.1.5 on 2021-08-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MouldQuality', '0004_audittrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrack',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='audittrack',
            name='both_side_done',
            field=models.BooleanField(default=False),
        ),
    ]
