# Generated by Django 3.1.5 on 2021-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MouldQuality', '0005_auto_20210810_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrack',
            name='godrej_auitor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='audittrack',
            name='supplier_audito',
            field=models.CharField(max_length=50),
        ),
    ]
