# Generated by Django 3.1.5 on 2021-08-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MouldQuality', '0006_auto_20210810_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='capa_data',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.CharField(max_length=100, null=True)),
                ('capa_comment', models.CharField(max_length=200, null=True)),
                ('capa_submitted', models.CharField(max_length=200, null=True)),
                ('capa_recv', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
