# Generated by Django 3.1.5 on 2021-08-04 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mould',
            fields=[
                ('mould_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mould_name', models.CharField(max_length=200)),
                ('cavity_number', models.IntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('general_maintaince_cleaning_threshold_value', models.IntegerField()),
                ('preventive_maintaince_clearning_thresold_value', models.IntegerField()),
                ('tool_life', models.IntegerField()),
                ('present_count', models.IntegerField()),
                ('moud_desc', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100)),
                ('raw_material', models.CharField(max_length=100)),
                ('part_weight', models.FloatField()),
                ('runner_weight', models.FloatField()),
                ('tonnage', models.FloatField()),
                ('cycle_time', models.FloatField()),
                ('number_of_shots_per_day', models.IntegerField()),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MouldUnload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mould_id', models.IntegerField()),
                ('mould_name', models.CharField(max_length=200)),
                ('cavity_number', models.CharField(max_length=200)),
                ('clause_1', models.BooleanField()),
                ('clause_2', models.BooleanField()),
                ('clause_3', models.BooleanField()),
                ('clause_4', models.BooleanField()),
                ('clause_5', models.BooleanField()),
                ('clause_6', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralCleaningPresent',
            fields=[
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mould_cleaning', serialize=False, to='mould.mould')),
                ('date_applied_for_cleaning', models.DateTimeField(auto_now_add=True)),
                ('date_get_back_from_cleaning', models.DateTimeField(null=True)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintainceArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied_for_maitaince', models.DateTimeField(null=True)),
                ('date_of_get_back_from_cleaning', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_pm_data', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintaince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied_for_maitaince', models.DateTimeField(auto_now_add=True)),
                ('date_of_get_back_from_cleaning', models.DateTimeField(null=True)),
                ('comment', models.CharField(max_length=200)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_pm_history', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='MouldStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_update', models.DateTimeField(auto_now_add=True)),
                ('count_increment', models.IntegerField()),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_status', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='MouldDailyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('date_time_of_update', models.DateTimeField(auto_now_add=True)),
                ('clause_1', models.BooleanField()),
                ('clause_2', models.BooleanField()),
                ('clause_3', models.BooleanField()),
                ('clause_4', models.BooleanField()),
                ('clause_5', models.BooleanField()),
                ('clause_6', models.BooleanField()),
                ('clause_7', models.BooleanField()),
                ('clause_8', models.BooleanField()),
                ('clause_9', models.BooleanField()),
                ('clause_10', models.BooleanField()),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Machine_Mould', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='MouldComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commented_date_time', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_chat', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralClearningArchieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied_for_cleaning', models.DateTimeField(null=True)),
                ('date_get_back_from_cleaning', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_gc_history', to='mould.mould')),
            ],
        ),
    ]
