# Generated by Django 3.1.5 on 2021-08-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouldDamageArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_name', models.CharField(max_length=200)),
                ('damage_occurued_on', models.DateTimeField(null=True)),
                ('damage_recovered_on', models.DateTimeField(auto_now_add=True)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_damage_archive', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='MouldDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_name', models.CharField(max_length=200)),
                ('damage_occurued_on', models.DateTimeField(auto_now_add=True)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_damage', to='mould.mould')),
            ],
        ),
    ]
