# Generated by Django 3.1.5 on 2021-08-09 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0002_moulddamage_moulddamagearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='moulddamage',
            name='damage_comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
