# Generated by Django 3.1.5 on 2021-08-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0003_moulddamage_damage_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mould',
            name='general_cleaning_maintance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mould',
            name='preventice_maintaince_count',
            field=models.IntegerField(default=0),
        ),
    ]
